import { ArrowLeft, ArrowRight, ArrowUpRight, Download, Github, Mail } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Architecture, ExternalAction, ProjectCard, SectionIntro } from './components/PortfolioUI'
import { PageMeta } from './components/Layout'
import { caseStudies, experiences, proofPoints, publications, site, skillGroups } from './data/site'

const description = 'Portfolio of Janice Benita F, an Information Technology undergraduate building explainable AI systems, computer-vision applications, backend services, analytics platforms, and reliable software.'

function ContactCTA() { return <section className="contact-cta"><div className="shell"><p className="kicker">Open to opportunities</p><h2>Let’s work on a problem that needs both technical depth and responsible judgment.</h2><p>I am open to AI/ML, applied AI, backend, and software-engineering internship or campus-placement opportunities.</p><div className="actions"><a className="button" href={`mailto:${site.email}`}><Mail size={17}/> Email Janice</a><a className="button secondary" href={site.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={16}/></a></div></div></section> }

export function HomePage() {
  const sentinel = caseStudies[0]
  return <><PageMeta title="Janice Benita F | AI/ML & Software Engineer" description={description}/>
    <section className="hero shell"><div className="hero-main"><p className="kicker">Chennai, India · Open to campus placements</p><h1><span>{site.name}</span>I build explainable AI systems, reliable software, and data-driven tools for real-world decisions.</h1><p className="hero-role">{site.role}</p><p className="hero-proof">Machine-learning intern at Larsen &amp; Toubro · 2 research papers · 95.7% computer-vision accuracy</p><div className="actions"><Link className="button" to="/work">View selected work <ArrowRight size={17}/></Link><Link className="button secondary" to="/resume">View résumé</Link><a className="text-link" href={site.github} target="_blank" rel="noreferrer"><Github size={16}/> GitHub</a></div></div><aside className="hero-note"><span>Working principle</span><p>“A system is more useful when its evidence, limitations, and human decision points remain visible.”</p><small>My work sits where models become dependable tools.</small></aside></section>
    <section className="proof-section shell" aria-labelledby="proof-title"><SectionIntro kicker="Selected evidence" title="Impact in context." copy="A compact view of verified outcomes across computer vision, analytics, research, and engineering delivery."/><div className="proof-grid">{proofPoints.map((item,index) => <article key={item.label}><span>0{index+1}</span><strong>{item.value}</strong><h3>{item.label}</h3><p>{item.context}</p></article>)}</div></section>
    <section className="section shell"><SectionIntro kicker="Flagship project" title="Reliability automation with a clear boundary." copy="SentinelOps investigates autonomously, verifies deterministically, and leaves approval with a person."/><ProjectCard project={sentinel} index={0}/><Architecture steps={sentinel.architecture}/></section>
    <section className="section shell"><SectionIntro kicker="Selected work" title="Systems designed to be understood."/><div className="project-list">{caseStudies.slice(1).map((p,i)=><ProjectCard key={p.slug} project={p} index={i+1}/>)}</div><Link className="text-link standalone" to="/work">Explore all case studies <ArrowRight size={16}/></Link></section>
    <section className="section shell split"><SectionIntro kicker="Experience" title="Learning through real engineering constraints."/><div className="experience-compact">{experiences.map((item,index)=><article key={item.company}><span>0{index+1}</span><div><p>{item.period}</p><h3>{item.company}</h3><strong>{item.role}</strong><p>{item.summary}</p></div></article>)}</div></section>
    <section className="section shell philosophy"><p className="kicker">How I work</p><blockquote>I am interested in the point where machine learning becomes a dependable system: where models need explanations, APIs need safeguards, data needs context, and automated actions still require responsible boundaries.</blockquote><Link className="text-link" to="/about">More about my approach <ArrowRight size={16}/></Link></section>
    <ContactCTA/>
  </>
}

export function WorkPage() { return <><PageMeta title="Selected Work | Janice Benita F" description="Case studies in AI reliability, explainable computer vision, clinical AI, and engineering analytics." path="/work"/><section className="page-head shell"><p className="kicker">Work / Case studies</p><h1>Engineering decisions, not just project summaries.</h1><p>Each case study explains the problem, system boundary, approach, validation, result, and limitation.</p></section><section className="section shell project-list">{caseStudies.map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</section><ContactCTA/></> }

export function CaseStudyPage() {
  const { slug } = useParams(); const project = caseStudies.find(item => item.slug === slug)
  if (!project) return <NotFoundPage />
  return <><PageMeta title={`${project.title} | Janice Benita F`} description={project.summary} path={`/work/${project.slug}`}/><article className="case-study">
    <header className="case-head shell"><Link className="text-link" to="/work"><ArrowLeft size={16}/> All work</Link><p className="kicker">{project.category} · {project.year}</p><h1>{project.title}<span>{project.subtitle}</span></h1><p className="case-summary">{project.summary}</p><div className="case-meta"><div><span>My role</span><strong>{project.role}</strong></div><div><span>Status</span><strong>Project / research work</strong></div><div><span>Focus</span><strong>{project.technologies.slice(0,3).join(' · ')}</strong></div></div></header>
    <div className="case-visual shell"><img src={project.image} alt={project.imageAlt} width="1200" height="800"/></div>
    <section className="case-section shell two-col"><h2>Problem and context</h2><div><h3>The problem</h3><p>{project.problem}</p><h3>Context</h3><p>{project.context}</p></div></section>
    <section className="case-section shell"><h2>System architecture</h2><Architecture steps={project.architecture} label={`${project.title} workflow`}/></section>
    <section className="case-section shell two-col"><h2>Technical approach</h2><div><ol className="number-list">{project.approach.map(item=><li key={item}>{item}</li>)}</ol><h3>Key engineering decisions</h3><ul>{project.decisions.map(item=><li key={item}>{item}</li>)}</ul></div></section>
    <section className="case-section shell evidence-panel"><div><p className="kicker">Validation</p><h2>How the work was checked.</h2><p>{project.validation}</p></div><div><p className="kicker">Verified results</p><ul>{project.results.map(item=><li key={item}>{item}</li>)}</ul></div></section>
    <section className="case-section shell two-col"><h2>Limits and responsibility</h2><div><ul>{project.limitations.map(item=><li key={item}>{item}</li>)}</ul>{project.responsibleUse && <aside className="responsible"><strong>Responsible-use boundary</strong><p>{project.responsibleUse}</p></aside>}</div></section>
    <section className="case-section shell two-col"><h2>Reflection</h2><div><h3>What I learned</h3><p>{project.lessons}</p><h3>Next steps</h3><p>{project.nextSteps}</p><div className="tags">{project.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="actions">{project.repositoryUrl && <ExternalAction href={project.repositoryUrl}>Repository</ExternalAction>}{project.publicationUrl && <ExternalAction href={project.publicationUrl}>Publication</ExternalAction>}</div></div></section>
  </article><ContactCTA/></>
}

export function ResearchPage() { return <><PageMeta title="Research | Janice Benita F" description="Applied research by Janice Benita F in engineering quality intelligence and explainable concrete crack detection." path="/research"/><section className="page-head shell"><p className="kicker">Research</p><h1>Applied research with careful claims.</h1><p>Work connecting model development, explainability, engineering analysis, and decision support.</p></section><section className="section shell publication-list">{publications.map((p,index)=><article key={p.title}><div><span>0{index+1}</span><strong className={`status ${p.status.toLowerCase()}`}>{p.status}</strong></div><div><p>{p.journal}</p><h2>{p.title}</h2><p>{p.detail}</p><div className="actions"><Link className="text-link" to={`/work/${p.relatedSlug}`}>Related case study <ArrowRight size={16}/></Link>{p.url && <a className="text-link" href={p.url} target="_blank" rel="noreferrer">DOI: {p.doi}<ArrowUpRight size={15}/></a>}</div></div></article>)}</section><section className="section shell achievements"><SectionIntro kicker="Recognition" title="Supporting evidence, kept in proportion."/><div><article><strong>Second Prize</strong><p>International Digital Dentistry Congress 2026 · Poster Presentation · Postgraduate Category</p><span>AI/ML Software Developer and Co-Author</span></article><article><strong>Runner-up</strong><p>CodeVerse Inter-Collegiate Technical Symposium</p></article></div></section><ContactCTA/></> }

export function AboutPage() { return <><PageMeta title="About | Janice Benita F" description="About Janice Benita F and her approach to explainable AI, reliable software, and responsible engineering." path="/about"/><section className="page-head shell"><p className="kicker">About</p><h1>I care about what happens after a model produces an answer.</h1></section><section className="about-story shell"><div><p className="lead">I am interested in the point where machine learning becomes a dependable system: where models need explanations, APIs need safeguards, data needs context, and automated actions still require responsible boundaries.</p><p>My work spans explainable computer vision, AI reliability agents, analytics platforms, backend development, and research. I enjoy understanding not only whether a system works, but how it fails, how it can be verified, and how people can trust its output.</p></div><aside><p className="kicker">Education</p><h2>St. Joseph’s College of Engineering</h2><p>Bachelor of Technology in Information Technology</p><dl><div><dt>Period</dt><dd>2023–2027</dd></div><div><dt>CGPA</dt><dd>8.30 / 10.00</dd></div></dl></aside></section><section className="section shell"><SectionIntro kicker="Technical toolkit" title="Grouped by the work they support."/><div className="skills-grid">{skillGroups.map((group,index)=><article key={group.title}><span>0{index+1}</span><h3>{group.title}</h3><ul>{group.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></section><ContactCTA/></> }

export function ResumePage() { return <><PageMeta title="Résumé | Janice Benita F" description="View or download the résumé of Janice Benita F, AI/ML and Software Engineer." path="/resume"/><section className="page-head shell resume-head"><div><p className="kicker">Résumé</p><h1>Experience and evidence, in one page.</h1><p>The PDF is text-selectable, ATS-friendly, and opens in the browser without a forced download.</p></div><div className="actions"><a className="button" href={site.resume} target="_blank" rel="noreferrer">Open PDF <ArrowUpRight size={16}/></a><a className="button secondary" href={site.resume} download><Download size={16}/> Download</a></div></section><section className="resume-preview shell"><object data={site.resume} type="application/pdf" aria-label="Janice Benita F résumé preview"><p>Your browser cannot display the PDF preview. <a href={site.resume}>Open the résumé PDF</a>.</p></object></section><ContactCTA/></> }

export function NotFoundPage() { return <><PageMeta title="Page not found | Janice Benita F" description="The requested portfolio page could not be found."/><section className="not-found shell"><p className="kicker">404 / Page not found</p><h1>This path does not lead to a case study.</h1><p>The work is still here. Return to the portfolio or browse the selected projects.</p><div className="actions"><Link className="button" to="/">Go home</Link><Link className="button secondary" to="/work">View work</Link></div></section></> }
